version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: journal_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Catatan: Gunakan path absolut yang valid di server untuk schema.sql jika memakai Swarm
      - /home/ubuntu/ansible-deployment/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: afifatulrohmah/journal-backend:latest
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: journal_db
      JWT_SECRET: my_super_secret_dev_key
      PORT: 3000
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: afifatulrohmah/journal-frontend:latest
    environment:
      VITE_API_URL: "http://54.224.248.145:3000" # <-- Perbaikan: Menggunakan titik dua (:)
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

volumes:
  db_data:
