version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: journal_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: journal_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: journal_backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: journal_db
      JWT_SECRET: my_super_secret_dev_key
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: journal_frontend
    environment:
      # SEKALIAN DIPERBAIKI: Ubah localhost ke IP Publik Manager agar browser laptopmu bisa konek ke API!
      VITE_API_URL=http://54.82.179.64:3000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    # --- PENEMPATANNYA DI SINI ---
    deploy:
      placement:
        constraints:
          - node.role == worker
    # -----------------------------
    restart: unless-stopped

volumes:
  db_data:
