version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: journal_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /home/ubuntu/ansible-deployment/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: afifatulrohmah/journal-backend:latest
    environment:
      DB_HOST: db
      DB_USER: user             # Diganti ke 'user' agar diizinkan koneksi remote dari container backend
      DB_PASSWORD: password     # Menggunakan password dari MYSQL_PASSWORD
      DB_NAME: journal_db
      JWT_SECRET: my_super_secret_dev_key
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: afifatulrohmah/journal-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

volumes:
  db_data:

# Direct komunikasi antar-node di Docker Swarm
networks:
  app-network:
    driver: overlay
